### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jimchen5209** [OKTW-Network/mc.oktw.one#20]
To Translate:

- [x] Rewrite EN Wiki(#23)
- [X] Chunkloader
- [X] HT Crafting Table
- [x] elevator
- [x] Teleporter(#14)
- [x] News
- [x] Materials(#14)
- [x] Wrench
- [x] Upgrades(#14)
- [x] Command
- [x] Custom Block Notify
- [x] Easy Recipe
- [x] Galaxy Manage
- [x] Introduction
- [x] Star Dust
- [x] Quick Start
- [x] Words
